version: '3.8'

services:
  backend:
    build:
      context: ./server
    container_name: brewluxe-backend
    ports:
      - "3000:3000"
    volumes:
      - ./server/brewluxe.db:/app/brewluxe.db
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ./frontend
    container_name: brewluxe-frontend
    ports:
      - "5520:80"
    depends_on:
      - backend
